spring:
  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false
  jpa:
    database: POSTGRESQL
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    url: jdbc:postgresql://localhost:5432/exemplo_security?createDatabaseIfNotExist=true
    password: 601034
    username: postgres
    driverClassName: org.postgresql.Driver
  security:
    token:
      secret: "exemplo-security"
      expiration_time: 30
  mail:
    properties:
      mail:
        smtp:
          starttls:
            enable: 'true'
          auth: 'true'
    host: smtp.gmail.com
    username: roberto.fmedeiros62@gmail.com
    password: "bbul jtmq otqv evgd"
    port: '587'